version: '3.8'

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - geoguessr-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  geoguessr:
    build:
      context: ./geoguessr
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - geoguessr-network
    depends_on:
      - api

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - geoguessr-network
    ports:
      - "3306:3306"

networks:
  geoguessr-network:
    driver: bridge

volumes:
  db-data:

