services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - geoguessr-network

  geoguessr:
    build:
      context: ./geoguessr
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - geoguessr-network

networks:
  geoguessr-network:
    driver: bridge
