name: Build and Deploy Docker App

on:
  push:
    branches:
      - main  # Déclenche l'action lors des pushs sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser l'OS Ubuntu pour exécuter les actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t geoguessr .

    - name: Notify (ou d'autres actions selon ton workflow)
      run: echo "Déploiement complet"
