name: Build and Deploy Docker App to Railway

# Déclenche l'action lors de chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify (ou d'autres actions selon ton workflow)
      run: echo "Déploiement complet"
